language: generic
env:
  global:
    - IDE_VERSION=1.8.5
  matrix:
    - BOARD="arduino:samd:mkrgsm1400"
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd;
    fi
  - buildExampleSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/$1/$1.ino; }
  - buildExampleToolsSketch() { arduino --verbose-build --verify --board $BOARD $PWD/examples/Tools/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch GsmWebClient
  - buildExampleSketch GsmWebServer
  - buildExampleSketch MakeVoiceCall
  - buildExampleSketch ReceiveSMS
  - buildExampleSketch ReceiveVoiceCall
  - buildExampleSketch SendSMS
  - buildExampleSketch GPRSPing
  - buildExampleSketch GsmSSLWebClient
  - buildExampleSketch GPRSUdpNtpClient
  - buildExampleSketch GsmLocation
  - buildExampleToolsSketch BandManagement
  - buildExampleToolsSketch ChooseRadioAccessTechnology
  - buildExampleToolsSketch GsmScanNetworks
  - buildExampleToolsSketch PinManagement
  - buildExampleToolsSketch TestGPRS
  - buildExampleToolsSketch TestModem
  - buildExampleToolsSketch TestWebServer
  - buildExampleToolsSketch SerialGSMPassthrough
